create a next.js modern and sleek auth, register will ask user for email and phone number then next step user will receive 6 chr otp numbers only once they verify otp they will be logged in show a list of 2 tools daily ending balances and statement analysis "https://openmca.com/ending_balance","https://openmca.com" use will choose where they want to go. for login user will enter phone number verify otp verify. 

implement api integration here is the base url.
https://openmca.com/auth/api/
otp sent here /auth/api/send-otp
response
res.json({ success: true });

otp verification here: /auth/api/verify-otp body const { phone, code } = req.body;
response:
res.cookie('session_id', sessionId, {
httpOnly: true,
secure: true,
sameSite: 'Strict'
});


    res.json({ success: true });
session verification
// Verify session (for Nginx auth_request)
app.get('/auth/api/verify', async (req, res) => {
try {
const sessionId = req.cookies.session_id;
if (!sessionId) return res.sendStatus(401);


    const db = getDb();
    const sessionsCol = db.collection('sessions');

    const session = await sessionsCol.findOne({
        sessionId,
        expiresAt: { $gt: new Date() }
    });

    if (!session) return res.sendStatus(401);
    res.sendStatus(200);
} catch (err) {
    console.error(err);
    res.status(500).send('Error verifying session');
}
});

that code is from backend to help you with the UI integration